[target.xtensa-esp32-none-elf]
runner = "espflash flash --monitor"
rustflags = ["-C", "link-arg=-Wl,-Tlinkall.x", "-C", "link-arg=-nostartfiles"]

[target.xtensa-esp32s3-none-elf]
runner = "espflash flash --monitor"
rustflags = ["-C", "link-arg=-Wl,-Tlinkall.x", "-C", "link-arg=-nostartfiles"]

[env]
ESP_LOG = "info"
