[target.'cfg(target_arch = "xtensa")']
runner = "espflash flash --monitor"
rustflags = [
  # GNU LD
  "-C", "link-arg=-Wl,-Tlinkall.x",
  "-C", "link-arg=-nostartfiles",
]

[env]
ESP_LOG = "info"

[unstable]
build-std = ["core", "alloc"]
